## Numpy array opreations


In [5]:
import numpy as np

In [16]:
arr = np.array([1,2,3,4])
print(f"basic slicing: {arr[0:4]}")
print(f"basic slicing with steps: {arr[0:4:2]}")
print(f"Negetive indexing: {arr[-4:-1]}")


basic slicing: [1 2 3 4]
basic slicing with steps: [1 3]
Negetive indexing: [1 2 3]


In [41]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Array: \n{arr2D}")
print(f"\nSpecific element: {arr2D[0,2]}")
print(f"\nEntire row: {arr2D[2]}")
print(f"\nEntire column: \n{arr2D[:,1].reshape(3,1)}")

Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Specific element: 3

Entire row: [7 8 9]

Entire column: 
[[2]
 [5]
 [8]]


## Sorting 

In [54]:
unsorted_arr = np.array([1,3,5,63,2,654,545,2,245,134])
print(f"Sorted array : \n {np.sort(unsorted_arr)}")

unsorted = np.array([[1,4,6,3,13,32],[1,45,234,5,4325,1]])
print(f"Sorted 2D array : \n {np.sort(unsorted,axis=0)}")


Sorted array : 
 [  1   2   2   3   5  63 134 245 545 654]
Sorted 2D array : 
 [[   1    4    6    3   13    1]
 [   1   45  234    5 4325   32]]


## Filtering of an array


In [56]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
odd_num = numbers[numbers % 2 != 0]
print(f"Odd values: {odd_num}")

Odd values: [1 3 5 7 9]


## Filter with mask



In [59]:
mask = numbers > 4
print(f"Numbers greater then 4: {numbers[mask]}")

Numbers greater then 4: [ 5  6  7  8  9 10]


## Fancy indexing and np.where()

In [12]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(numbers[where_result])

[1 3 5]
[ 6  7  8  9 10]


## Condition based array

In [26]:
condition_array = np.where(numbers != 1,numbers == numbers,numbers)
print(numbers[condition_array])

[2 2 2 2 2 2 2 2 2 2]


## Adding and removing data

In [37]:
arr1 = np.arange(5)
arr2 = np.arange(5)

merged_arr = np.concatenate((arr1,arr2))
merged_arr


array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

### Array compatiblity


In [50]:
arr1 = np.arange(5)
arr2 = np.arange(6,11)
arr3 = np.arange(11,16)

print(f"Compatiblity shape {arr1.ndim == arr2.ndim}")

Compatiblity shape True


### Adding new row and column

In [59]:
new_arr = np.array([[1,2,3],[4,5,6]])
new_row = np.array([[7,8,9]])
arr = np.vstack((new_arr,new_row))
print(f"New added row\n{arr}")
new_column = np.array([[10],[11],[12]])
arr = np.hstack((arr,new_column))
print(f"New added column\n{arr}")


New added row
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New added column
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
