Numpy arrays and Basics


In [10]:
import numpy as np
import time

creating array from list


In [ ]:
arr_1D = np.array([1,2,3,4,5])
print(arr_1D)

arr_2D = np.array([[1,2,3,4],[1,2,3,4]])
print(f"2D array: {arr_2D}")

[1 2 3 4 5]
2D array: [[1 2 3 4]
 [1 2 3 4]]


List vs Numpy array

In [11]:
py_list = [1,2,3]
print(f"Multiplication in list {py_list * 2}")
np_array = np.array([1,2,3])
print(f"Multiplication in array {np_array * 2}")




Multiplication in list [1, 2, 3, 1, 2, 3]
Multiplication in array [2 4 6]


In [29]:
start = time.time()
py_list = [i*2 for i in range(10000000)]
print(f"\n list opreation time: {time.time() - start}")
start = time.time()
np_array = np.arange(10000000) * 2
print(f"\n Array opreation time: {time.time() - start}")



 list opreation time: 0.5178415775299072

 Array opreation time: 0.04661154747009277


creating an array from scratch


In [40]:
zeros = np.zeros((3,4))
zeros
ones = np.ones((3,4))
ones
const = np.full((2,3),1)
const
rand = np.random.random((2,4))
rand

sequence = np.arange(0,12,2)
sequence

array([ 0,  2,  4,  6,  8, 10])

Vector ,matrix and tensor

In [44]:
vector = np.array([1,2,3])
vector

matrix = np.array([[1,2,3], [1,2,3]])
matrix

tensor = np.array([[[1,2], [1,2]], [[1,2] , [1,2]]])
tensor

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

Array properties